project:
  type: website

website:
  description: "Tłumaczę świat przy pomocy liczb."
  site-url: "https://piotr-urbanski.netlify.app"
  title: "Między nami a liczbami"
  navbar:
    left: 
    - text: O mnie
      href: about.qmd
    right:
    - icon: linkedin
      href: https://linkedin.com/in/urbnski/
    - icon: github
      href: https://github.com
    - icon: envelope
      href: mailto:piotr_urbanski@o2.pl
        
format:
  html:
    theme:
      - zephyr
    css: styles.css

editor: visual

