project:
  type: website

website:
  description: "Blog osobisty"
  site-url: "https://piotr-urbanski.netlify.app"
  title: "Piotr Urbański"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/p-urbanski
        
format:
  html:
    theme:
      - litera
    css: styles.css

editor: visual

